
import java.awt.Toolkit;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author chupa
 */
public class gameFrame extends javax.swing.JFrame {

    /**
     * Creates new form gameFrame
     */
    public gameFrame() {
        initComponents();
        this.setResizable(true);
        setTitle("Game Hub");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("G H.png")));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMole = new javax.swing.JLabel();
        btnTicTacToe = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moleIcon.png"))); // NOI18N
        btnMole.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMoleMouseClicked(evt);
            }
        });
        getContentPane().add(btnMole, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 80, 70));

        btnTicTacToe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTicTacToe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/220px-Wild_tic-tac-toe.svg.png"))); // NOI18N
        btnTicTacToe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTicTacToe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTicTacToeMouseClicked(evt);
            }
        });
        getContentPane().add(btnTicTacToe, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 90, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameMenu2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoleMouseClicked
            WackaMole MOLE = new WackaMole();
            MOLE.show();
            dispose();
    }//GEN-LAST:event_btnMoleMouseClicked

    private void btnTicTacToeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTicTacToeMouseClicked
        XoGame XOXO = new XoGame();
        XOXO.show();
        dispose();
    }//GEN-LAST:event_btnTicTacToeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnMole;
    private javax.swing.JLabel btnTicTacToe;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
