
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author John Andrew Borabo
 */
public class WackaMole extends javax.swing.JFrame {
    private final ImageIcon moleImage;
    int score = 0;
    int counter = 30;
    Boolean isIt = false;
    
    
    
    
    public WackaMole() {
        initComponents();
        moleImage = new ImageIcon(getClass().getResource("/mole.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        mole1 = new javax.swing.JLabel();
        mole2 = new javax.swing.JLabel();
        mole3 = new javax.swing.JLabel();
        mole4 = new javax.swing.JLabel();
        mole5 = new javax.swing.JLabel();
        mole6 = new javax.swing.JLabel();
        mole7 = new javax.swing.JLabel();
        mole8 = new javax.swing.JLabel();
        mole9 = new javax.swing.JLabel();
        txtScore = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mole1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mole1MouseClicked(evt);
            }
        });
        getContentPane().add(mole1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 90, 100));

        mole2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mole.png"))); // NOI18N
        mole2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mole2MouseClicked(evt);
            }
        });
        getContentPane().add(mole2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 90, 100));

        mole3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mole3MouseClicked(evt);
            }
        });
        getContentPane().add(mole3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 90, 100));

        mole4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mole4MouseClicked(evt);
            }
        });
        getContentPane().add(mole4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 90, 100));

        mole5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mole5MouseClicked(evt);
            }
        });
        getContentPane().add(mole5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 90, 100));

        mole6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mole6MouseClicked(evt);
            }
        });
        getContentPane().add(mole6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 90, 100));

        mole7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mole7MouseClicked(evt);
            }
        });
        getContentPane().add(mole7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 90, 100));

        mole8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mole8MouseClicked(evt);
            }
        });
        getContentPane().add(mole8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 90, 100));

        mole9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mole9MouseClicked(evt);
            }
        });
        getContentPane().add(mole9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 90, 100));

        txtScore.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        txtScore.setForeground(new java.awt.Color(51, 51, 51));
        txtScore.setText("Score: 0");
        getContentPane().add(txtScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 100, 20));

        txtTime.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        txtTime.setForeground(new java.awt.Color(51, 51, 51));
        txtTime.setText("Time: 30");
        getContentPane().add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 80, 20));

        btnStart.setBackground(new java.awt.Color(0, 204, 204));
        btnStart.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 90, 30));

        btnExit.setBackground(new java.awt.Color(51, 255, 0));
        btnExit.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        btnExit.setText("exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wackmolebg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void handleClick(java.awt.event.MouseEvent evt, JLabel current, JLabel next) {
    current.setVisible(false);
    next.setIcon(moleImage);
    txtScore.setText("Score: " + (++score));
}
    
    private void mole2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mole2MouseClicked
        handleClick(evt, mole2, mole1);
        mole1.setVisible(true);

    }//GEN-LAST:event_mole2MouseClicked

    private void mole1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mole1MouseClicked
        handleClick(evt, mole1, mole3);
        mole3.setVisible(true);
    }//GEN-LAST:event_mole1MouseClicked

    private void mole3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mole3MouseClicked
        handleClick(evt, mole3, mole4);
        mole4.setVisible(true);
    }//GEN-LAST:event_mole3MouseClicked

    private void mole4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mole4MouseClicked
        handleClick(evt, mole4, mole5);
        mole5.setVisible(true);
    }//GEN-LAST:event_mole4MouseClicked

    private void mole5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mole5MouseClicked
        handleClick(evt, mole5, mole6);
        mole6.setVisible(true);
    }//GEN-LAST:event_mole5MouseClicked

    private void mole6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mole6MouseClicked
        handleClick(evt, mole6, mole7);
        mole7.setVisible(true);
    }//GEN-LAST:event_mole6MouseClicked

    private void mole7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mole7MouseClicked
        handleClick(evt, mole7, mole8);
        mole8.setVisible(true);
    }//GEN-LAST:event_mole7MouseClicked

    private void mole8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mole8MouseClicked
        handleClick(evt, mole8, mole9);
        mole9.setVisible(true);
    }//GEN-LAST:event_mole8MouseClicked

    private void mole9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mole9MouseClicked
        handleClick(evt, mole9, mole2);
        mole2.setVisible(true);
    }//GEN-LAST:event_mole9MouseClicked

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        txtScore.setText("Score: 0");
        Timer timer = new Timer();
        counter = 30;
        TimerTask task = new TimerTask(){
            public void run(){
                txtTime.setText("Time: " +Integer.toString(counter));
                counter --;
                if(counter == -1){
                    timer.cancel();
                } else if(isIt){
                    timer.cancel();
                    isIt = false;
                }
            }
        };
        timer.scheduleAtFixedRate(task, 0, 1000);
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        gameFrame MENU = new gameFrame();
        MENU.show();
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WackaMole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WackaMole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WackaMole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WackaMole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WackaMole().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel mole1;
    private javax.swing.JLabel mole2;
    private javax.swing.JLabel mole3;
    private javax.swing.JLabel mole4;
    private javax.swing.JLabel mole5;
    private javax.swing.JLabel mole6;
    private javax.swing.JLabel mole7;
    private javax.swing.JLabel mole8;
    private javax.swing.JLabel mole9;
    private javax.swing.JLabel txtScore;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables

}
